# Install and configure the primary DNS server
---
- name: Install bind9 bind9utils bind9-doc
  apt:
    name:
    - bind9
    - bind9utils
    - bind9-doc
    state: present
    update_cache: yes
    autoclean: yes
    autoremove: yes
    
- name: Update bind9 to IPv4
  replace:
    path: /etc/default/bind9
    regexp: '^OPTIONS="-u bind"$'
    replace: 'OPTIONS="-4 -u bind"'

- name:
  file:
    path: /var/cache/bind/zones
    state: directory
    owner: bind
    group: bind
    mode: 2775
    
- name: 
  copy:
    src: "{{ item }}"
    dest: /etc/bind/
    owner: root
    group: bind
    mode: 0644
  with_fileglob:
    - ./files/*
    
- name: 
  copy:
    src: "{{ item }}"
    dest: /etc/bind/zones/
    owner: root
    group: bind
    mode: 0644
  with_fileglob:
    - ./files/zones/*

- name: Check configuration
  command: named-checkconf
  
- name: Restart bind9 service
  service:
    name: bind9
    state: restarted